# describe un workflow de GitHub Actions que automatiza el proceso de CI/CD (Integración Continua y Despliegue Continuo) para una aplicación en un clúster de Minikube
name: CI/CD for Minikube Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3 #ste paso utiliza una acción preconfigurada de GitHub para clonar el código fuente del repositorio en el entorno de ejecución del runner

    # 2. Configurar Minikube
    - name: Set up Minikube #Este paso instala Minikube en el runner
      run: | #Se actualizan los paquetes del sistema, se instala conntrack (una herramienta necesaria para Minikube), se descarga la última versión de Minikube y finalmente se inicia Minikube.
        sudo apt-get update
        sudo apt-get install -y conntrack
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start

    # 3. Configurar Docker para usar Minikube
    - name: Configure Docker to use Minikube
      run: eval $(minikube docker-env) #Este comando configura Docker para que utilice el entorno Docker de Minikube
    
    # 4.1. Construir el proyecto con Maven
    - name: Build project
      run: mvn clean package

    # Verificar archivos generados
    - name: List files
      run: ls -l target

    # 4. Construir la imagen Docker
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/image-service-for-minikube:latest .


    # 5. Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    # 6. Subir la imagen a Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/image-service-for-minikube:latest

    # Crear o actualizar el Deployment
    - name: Apply Deployment
      run: kubectl apply -f deployment.yaml

    # 7. Aplicar cambios en Kubernetes
    - name: Update Kubernetes Deployment
      run: | #Este bloque de código en el archivo de GitHub Actions actualiza el Deployment de Kubernetes y aplica los cambios de la nueva imagen Docker en el clúster de Minikube. 
        kubectl set image deployment/deployment-service-for-minikube \
        container-service-for-minikube=${{ secrets.DOCKER_USERNAME }}/image-service-for-minikube:tagname
        kubectl rollout status deployment/deployment-service-for-minikube
